# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f37c579d9f576cde0115dc4fb25f214e72b608ffdda5d46fa5640c3281437ba5ce0e628916f3c610f1fd8aaaaf53b24f93f66f80fd735fa660ffaab2ff4d77

test:
  secret_key_base: 74a13ac6be8b111d6480d5c664fbb7185d18a457196599f27d1dfc446b1fc234fa2f28f28b41cffa6b3b418275a23142cdaa2b703e2992d42706fc378dcb151f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
